name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          cd my-app-local/password-generator-app
          npm install && npm start
      - run: |
          npm install -g artillery 
          artillery run my-app-local/password-generator-app/loadtest/loadtest.yaml
    
  publish_image:   
    runs-on: ubuntu-latest
    needs: build
    steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: build image
              run: |
                docker build ./my-app-local/password-generator-app -t thiagousa/demo:latest
            - name: push image to docker hub
              run: |
                docker login -u thiagousa -p ${{ secrets.DOCKER_HUB_TOKEN }}
                docker push thiagousa/demo:latest